отправка qr кодов и ReplyKeyboard
VeryBigSad/food-ticket-backend pull request #7
Opened 2022-10-26 17:30 UTC by maVovk

2022-10-26 18:34 UTC, VeryBigSad requested changes

2022-10-26 18:34 UTC, VeryBigSad commented on tgbot/handlers/food_tickets/handlers.py
> +EXPIRATION_TIME = datetime.timedelta(minutes=15)
все хорошо ток вот это бы вынести либо в settings.py либо в отдельный файл типа tgbot/constants.py т.к. ну слишком важная перменная

2022-10-26 18:34 UTC, VeryBigSad commented on tgbot/handlers/food_tickets/qr_codes.py
> +    encoded = rc4.rc4(data, os.environ['ENCRYPTION_KEY'])
получить значение из settings.py где его получать из os.env

2022-10-26 18:34 UTC, VeryBigSad commented on requirements.txt
>  ipython==8.5.0  # enhanced python interpreter
зачем

2022-10-26 18:34 UTC, VeryBigSad commented on tgbot/handlers/food_tickets/handlers.py
> +    update.message.reply_photo(photo=qr)
добавить подпись что expiration_time времени осталось на заюзать это и все, отлично

2022-10-26 18:34 UTC, VeryBigSad commented on requirements.txt
>  ipython==8.5.0  # enhanced python interpreter
а, изменение нормальное
не понял зачем там ipython стоит

2022-10-26 19:50 UTC, VeryBigSad requested changes

2022-10-26 19:50 UTC, VeryBigSad commented on tgbot/handlers/messages/handlers.py
> +def register(code: str, u):
вынести в отдельный файл мб

2022-10-26 19:50 UTC, VeryBigSad commented on tgbot/handlers/onboarding/handlers.py
> +    if hasattr(u, 'student'):
тут мб баг может быть, я бы писал `hasattr(u, 'student) and u.student`

2022-10-26 19:50 UTC, VeryBigSad commented on tgbot/handlers/onboarding/handlers.py
> +    # TODO: переделать на conversation
да
https://docs.python-telegram-bot.org/en/v20.0a4/examples.conversationbot2.html#conversationbot2-diagram
игнорируй async, у нас немного олдовая версия

2022-10-26 19:50 UTC, VeryBigSad commented on tgbot/handlers/onboarding/stickers.py
> +    'DO_NOT_CARE': 'CAACAgIAAxkBAAEGHNxjTEiepf7K1JhAzOsiOSjfs02UtAAC5BcAApI90EslNSSrAZreXyoE',
перенести в tgbot/utils/stickers.py (или какой-то такой путь) тк стикеры могут пересекаться

2022-10-26 19:50 UTC, VeryBigSad commented on tgbot/handlers/onboarding/keyboards.py
> +    if registered:
это прям отлично но надо бы желательно как-то заменить /комманда на текст
просто в dispatcher.py добавь мессаге хандлер с regex фильтер типа r'^Получить код 💋' и ВРОДЕ должно сработать
функцию на этот хандлер поставь ту же что и на /get_code

2022-10-26 19:50 UTC, VeryBigSad commented on tgbot/dispatcher.py
> +    dp.add_handler(CommandHandler("back", onboarding_handlers.command_wait))
это точно надо убрать и сделать так чтобы эта комнада была ИСКЛЮЧИТЕЛЬНО в conversation_handlers

2022-10-27 11:48 UTC, VeryBigSad approved these changes
хорош

2022-10-27 17:43 UTC, maVovk commented
`bot.send_message(chat_id=share_to_student.telegram_account.user_id, text=static_text.someone_shared_ticket_with_you.format(
        first_name=u.student.first_name,
        type=food_ticket.type,
        date_usable_at=food_ticket.date_usable_at
    ))

    bot.send_message(chat_id=u.user_id, text=static_text.share_qr_code_success.format(
        telegram_account=share_to_student.telegram_account.tg_str
    ))`
а тут специально отправка идёт не через update.message.reply_text?

2022-10-27 18:34 UTC, maVovk commented on tgbot/handlers/messages/handlers.py
> +def register(code: str, u):
я всё раскидал и файлам и снёс

2022-10-27 20:19 UTC, VeryBigSad commented
> ```
> bot.send_message(chat_id=share_to_student.telegram_account.user_id, 
>         text=static_text.someone_shared_ticket_with_you.format(
>         first_name=u.student.first_name,
>         type=food_ticket.type,
>         date_usable_at=food_ticket.date_usable_at
>     ))
> bot.send_message(chat_id=u.user_id, text=static_text.share_qr_code_success.format(
>         telegram_account=share_to_student.telegram_account.tg_str
> ))
> ```
> 
> а тут специально отправка идёт не через update.message.reply_text? в food_tickets.share_callback_handler

да, т.к. мы отправляем не тому кто это написал, а тому кому отправили талончик

2022-10-27 20:27 UTC, VeryBigSad approved these changes
да вроде все норм, чуть позже посмотрю на код уже в editor тк так это тяжело

2022-10-27 20:27 UTC, VeryBigSad commented on tgbot/handlers/conversations/handlers.py
> +    fallbacks=[CommandHandler("back", onboarding_handlers.command_wait)]
добавь ко всем conversation handler еще fallback текстом просто "назад" с эмодзи стрелки и вставь везде клавиатуры с таким текстом, чтобы красиво было

2022-10-27 20:27 UTC, VeryBigSad commented on tgbot/handlers/onboarding/handlers.py
> +    # тут потом надо будет сделать штуку, которая отправляет отчёт админам
сделай просто чтобы срала в admin груп чат, куда уже ошибки кидаются

2022-10-27 20:27 UTC, VeryBigSad commented on tgbot/handlers/conversations/handlers.py
> +    fallbacks=[CommandHandler("back", onboarding_handlers.command_wait)]
везде в ConversationHandler'ах, конечно

2022-10-28 06:51 UTC, merged